# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'Falta el título'
tagline:          'Falta el subtítulo'
description:      'Falta la descripción'
url:              https://mper-bcn-ny.github.io/2017-metro
baseurl:          /2017-metro/

author:
  name:           'Estudiantes del 2016/2017'
  url:            https://la22.org/somosla22/

paginate:         20

# Custom vars
version:          2.1.0

